Update pip update (#511)
## Changes
- Update of pip command as per the recommendation on the workflow run
```
Notice:  To update, run: python.exe -m pip install --upgrade pip
ERROR: To modify pip, please run the following command:
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe -m pip install --upgrade pip

```
## Checklist
<!-- Put an `x` in the boxes. All tasks must be completed and boxes
checked before merging. -->
- [ ] 🤖 This change is covered by unit tests (if applicable).
- [ ] 🤹 Manual testing has been performed (if necessary).
- [x] 🛡️ Security impacts have been considered (if relevant).
- [ ] 📖 Documentation updates are complete (if required).
- [ ] 🧠 Third-party dependencies and TPIP updated (if required).